In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df=pd.read_csv('customer.csv')

In [3]:
df

    age  gender   review education purchased
0    33    Male     Poor        PG       Yes
1    20  Female  Average    School        No
2    25  Female     Good        UG        No
3    51  Female     Poor        UG        No
4    29    Male     Poor    School        No
..  ...     ...      ...       ...       ...
75   43    Male     Good        PG       Yes
76   36  Female     Good        PG       Yes
77   45    Male  Average        UG       Yes
78   51    Male  Average        UG        No
79   59  Female     Poor        UG       Yes

[80 rows x 5 columns]

In [4]:
# so see the dataset we first identify what is nominal and what is ordinal so 'review',education,is ordinal so we solve thruogh ordinal encoding
# the out put in also catogorical so we used label encoding on this out put
dff=df.iloc[:,2:]

In [5]:
dff.head()

    review education purchased
0     Poor        PG       Yes
1  Average    School        No
2     Good        UG        No
3     Poor        UG        No
4     Poor    School        No

In [26]:
from sklearn.model_selection import train_test_split

In [27]:

x_train,x_test,y_train,y_test= train_test_split(dff.iloc[:,0:2],dff.iloc[:,-1],test_size=0.2)

In [28]:
x_train

     review education
19     Good        UG
62  Average        PG
14     Poor    School
4      Poor    School
47     Good    School
..      ...       ...
18  Average        PG
56     Good    School
20     Poor        PG
37     Poor    School
52     Good        PG

[64 rows x 2 columns]

In [29]:
y_train

19    Yes
62    Yes
14     No
4      No
47     No
     ...
18     No
56    Yes
20    Yes
37    Yes
52     No
Name: purchased, Length: 64, dtype: object

In [9]:
x_test.shape

(16, 2)

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
give=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
# WE CATEGORIZE  the value and on base of that value will be give the higher have high value and less have less value

In [12]:
give.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [13]:
x_train=give.transform(x_train)
x_test=give.transform(x_test)

In [14]:
x_train   # now see the data is covert to numerical from catagorical

array([[2., 1.],
       [1., 1.],
       [1., 2.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.]])

In [15]:
#now for output colume  to label encode it

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
lee=LabelEncoder()

In [34]:
lee.fit(y_train)

LabelEncoder()

In [35]:
lee.classes_

array(['No', 'Yes'], dtype=object)

In [36]:
y_train=lee.transform(y_train)
y_test=lee.transform(y_test)

In [40]:
y_train[2]

np.int64(0)

In [22]:
y_test

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1])